// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/pulse/internal/service (interfaces: JobService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/job_mock.go -package=mocks github.com/bete7512/pulse/internal/service JobService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bete7512/pulse/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockJobService is a mock of JobService interface.
type MockJobService struct {
	ctrl     *gomock.Controller
	recorder *MockJobServiceMockRecorder
	isgomock struct{}
}

// MockJobServiceMockRecorder is the mock recorder for MockJobService.
type MockJobServiceMockRecorder struct {
	mock *MockJobService
}

// NewMockJobService creates a new mock instance.
func NewMockJobService(ctrl *gomock.Controller) *MockJobService {
	mock := &MockJobService{ctrl: ctrl}
	mock.recorder = &MockJobServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobService) EXPECT() *MockJobServiceMockRecorder {
	return m.recorder
}

// CancelJob mocks base method.
func (m *MockJobService) CancelJob(ctx context.Context, jobID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelJob", ctx, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelJob indicates an expected call of CancelJob.
func (mr *MockJobServiceMockRecorder) CancelJob(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelJob", reflect.TypeOf((*MockJobService)(nil).CancelJob), ctx, jobID)
}

// CompleteJob mocks base method.
func (m *MockJobService) CompleteJob(ctx context.Context, jobID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteJob", ctx, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteJob indicates an expected call of CompleteJob.
func (mr *MockJobServiceMockRecorder) CompleteJob(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteJob", reflect.TypeOf((*MockJobService)(nil).CompleteJob), ctx, jobID)
}

// FailJob mocks base method.
func (m *MockJobService) FailJob(ctx context.Context, jobID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailJob", ctx, jobID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailJob indicates an expected call of FailJob.
func (mr *MockJobServiceMockRecorder) FailJob(ctx, jobID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailJob", reflect.TypeOf((*MockJobService)(nil).FailJob), ctx, jobID, reason)
}

// GetJob mocks base method.
func (m *MockJobService) GetJob(ctx context.Context, jobID string) (*domain.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", ctx, jobID)
	ret0, _ := ret[0].(*domain.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJob indicates an expected call of GetJob.
func (mr *MockJobServiceMockRecorder) GetJob(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockJobService)(nil).GetJob), ctx, jobID)
}

// Heartbeat mocks base method.
func (m *MockJobService) Heartbeat(ctx context.Context, jobID, workerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Heartbeat", ctx, jobID, workerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Heartbeat indicates an expected call of Heartbeat.
func (mr *MockJobServiceMockRecorder) Heartbeat(ctx, jobID, workerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Heartbeat", reflect.TypeOf((*MockJobService)(nil).Heartbeat), ctx, jobID, workerID)
}

// ListPendingJobsByTopics mocks base method.
func (m *MockJobService) ListPendingJobsByTopics(ctx context.Context, topics []string) ([]domain.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingJobsByTopics", ctx, topics)
	ret0, _ := ret[0].([]domain.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingJobsByTopics indicates an expected call of ListPendingJobsByTopics.
func (mr *MockJobServiceMockRecorder) ListPendingJobsByTopics(ctx, topics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingJobsByTopics", reflect.TypeOf((*MockJobService)(nil).ListPendingJobsByTopics), ctx, topics)
}

// PendingJobs mocks base method.
func (m *MockJobService) PendingJobs(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingJobs", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingJobs indicates an expected call of PendingJobs.
func (mr *MockJobServiceMockRecorder) PendingJobs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingJobs", reflect.TypeOf((*MockJobService)(nil).PendingJobs), ctx)
}

// StartJob mocks base method.
func (m *MockJobService) StartJob(ctx context.Context, jobID, workerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartJob", ctx, jobID, workerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartJob indicates an expected call of StartJob.
func (mr *MockJobServiceMockRecorder) StartJob(ctx, jobID, workerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartJob", reflect.TypeOf((*MockJobService)(nil).StartJob), ctx, jobID, workerID)
}

// Submit mocks base method.
func (m *MockJobService) Submit(ctx context.Context, topic string, payload []byte) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, topic, payload)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockJobServiceMockRecorder) Submit(ctx, topic, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockJobService)(nil).Submit), ctx, topic, payload)
}
