// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/pulse/internal/service (interfaces: JobReader)
//
// Generated by this command:
//
//	mockgen -destination=mocks/jobreader_mock.go -package=mocks github.com/bete7512/pulse/internal/service JobReader
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bete7512/pulse/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockJobReader is a mock of JobReader interface.
type MockJobReader struct {
	ctrl     *gomock.Controller
	recorder *MockJobReaderMockRecorder
	isgomock struct{}
}

// MockJobReaderMockRecorder is the mock recorder for MockJobReader.
type MockJobReaderMockRecorder struct {
	mock *MockJobReader
}

// NewMockJobReader creates a new mock instance.
func NewMockJobReader(ctrl *gomock.Controller) *MockJobReader {
	mock := &MockJobReader{ctrl: ctrl}
	mock.recorder = &MockJobReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobReader) EXPECT() *MockJobReaderMockRecorder {
	return m.recorder
}

// GetJob mocks base method.
func (m *MockJobReader) GetJob(ctx context.Context, jobID string) (*domain.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", ctx, jobID)
	ret0, _ := ret[0].(*domain.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJob indicates an expected call of GetJob.
func (mr *MockJobReaderMockRecorder) GetJob(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockJobReader)(nil).GetJob), ctx, jobID)
}

// ListPendingJobsByTopics mocks base method.
func (m *MockJobReader) ListPendingJobsByTopics(ctx context.Context, topics []string) ([]domain.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingJobsByTopics", ctx, topics)
	ret0, _ := ret[0].([]domain.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingJobsByTopics indicates an expected call of ListPendingJobsByTopics.
func (mr *MockJobReaderMockRecorder) ListPendingJobsByTopics(ctx, topics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingJobsByTopics", reflect.TypeOf((*MockJobReader)(nil).ListPendingJobsByTopics), ctx, topics)
}

// PendingJobs mocks base method.
func (m *MockJobReader) PendingJobs(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingJobs", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingJobs indicates an expected call of PendingJobs.
func (mr *MockJobReaderMockRecorder) PendingJobs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingJobs", reflect.TypeOf((*MockJobReader)(nil).PendingJobs), ctx)
}
