// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/pulse/internal/service (interfaces: JobWriter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/jobwriter_mock.go -package=mocks github.com/bete7512/pulse/internal/service JobWriter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockJobWriter is a mock of JobWriter interface.
type MockJobWriter struct {
	ctrl     *gomock.Controller
	recorder *MockJobWriterMockRecorder
	isgomock struct{}
}

// MockJobWriterMockRecorder is the mock recorder for MockJobWriter.
type MockJobWriterMockRecorder struct {
	mock *MockJobWriter
}

// NewMockJobWriter creates a new mock instance.
func NewMockJobWriter(ctrl *gomock.Controller) *MockJobWriter {
	mock := &MockJobWriter{ctrl: ctrl}
	mock.recorder = &MockJobWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobWriter) EXPECT() *MockJobWriterMockRecorder {
	return m.recorder
}

// CancelJob mocks base method.
func (m *MockJobWriter) CancelJob(ctx context.Context, jobID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelJob", ctx, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelJob indicates an expected call of CancelJob.
func (mr *MockJobWriterMockRecorder) CancelJob(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelJob", reflect.TypeOf((*MockJobWriter)(nil).CancelJob), ctx, jobID)
}

// CompleteJob mocks base method.
func (m *MockJobWriter) CompleteJob(ctx context.Context, jobID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteJob", ctx, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteJob indicates an expected call of CompleteJob.
func (mr *MockJobWriterMockRecorder) CompleteJob(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteJob", reflect.TypeOf((*MockJobWriter)(nil).CompleteJob), ctx, jobID)
}

// FailJob mocks base method.
func (m *MockJobWriter) FailJob(ctx context.Context, jobID, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailJob", ctx, jobID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailJob indicates an expected call of FailJob.
func (mr *MockJobWriterMockRecorder) FailJob(ctx, jobID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailJob", reflect.TypeOf((*MockJobWriter)(nil).FailJob), ctx, jobID, reason)
}

// Heartbeat mocks base method.
func (m *MockJobWriter) Heartbeat(ctx context.Context, jobID, workerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Heartbeat", ctx, jobID, workerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Heartbeat indicates an expected call of Heartbeat.
func (mr *MockJobWriterMockRecorder) Heartbeat(ctx, jobID, workerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Heartbeat", reflect.TypeOf((*MockJobWriter)(nil).Heartbeat), ctx, jobID, workerID)
}

// StartJob mocks base method.
func (m *MockJobWriter) StartJob(ctx context.Context, jobID, workerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartJob", ctx, jobID, workerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartJob indicates an expected call of StartJob.
func (mr *MockJobWriterMockRecorder) StartJob(ctx, jobID, workerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartJob", reflect.TypeOf((*MockJobWriter)(nil).StartJob), ctx, jobID, workerID)
}

// Submit mocks base method.
func (m *MockJobWriter) Submit(ctx context.Context, topic string, payload []byte, priority int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, topic, payload, priority)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockJobWriterMockRecorder) Submit(ctx, topic, payload, priority any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockJobWriter)(nil).Submit), ctx, topic, payload, priority)
}
