// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/pulse/internal/service (interfaces: PauseControlService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/pausecontrol_mock.go -package=mocks github.com/bete7512/pulse/internal/service PauseControlService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repos "github.com/bete7512/pulse/internal/repos"
	gomock "go.uber.org/mock/gomock"
)

// MockPauseControlService is a mock of PauseControlService interface.
type MockPauseControlService struct {
	ctrl     *gomock.Controller
	recorder *MockPauseControlServiceMockRecorder
	isgomock struct{}
}

// MockPauseControlServiceMockRecorder is the mock recorder for MockPauseControlService.
type MockPauseControlServiceMockRecorder struct {
	mock *MockPauseControlService
}

// NewMockPauseControlService creates a new mock instance.
func NewMockPauseControlService(ctrl *gomock.Controller) *MockPauseControlService {
	mock := &MockPauseControlService{ctrl: ctrl}
	mock.recorder = &MockPauseControlServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPauseControlService) EXPECT() *MockPauseControlServiceMockRecorder {
	return m.recorder
}

// Pause mocks base method.
func (m *MockPauseControlService) Pause(ctx context.Context, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pause", ctx, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pause indicates an expected call of Pause.
func (mr *MockPauseControlServiceMockRecorder) Pause(ctx, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pause", reflect.TypeOf((*MockPauseControlService)(nil).Pause), ctx, reason)
}

// Prime mocks base method.
func (m *MockPauseControlService) Prime(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prime", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Prime indicates an expected call of Prime.
func (mr *MockPauseControlServiceMockRecorder) Prime(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prime", reflect.TypeOf((*MockPauseControlService)(nil).Prime), ctx)
}

// Resume mocks base method.
func (m *MockPauseControlService) Resume(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resume indicates an expected call of Resume.
func (mr *MockPauseControlServiceMockRecorder) Resume(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockPauseControlService)(nil).Resume), ctx)
}

// Run mocks base method.
func (m *MockPauseControlService) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockPauseControlServiceMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockPauseControlService)(nil).Run), ctx)
}

// Status mocks base method.
func (m *MockPauseControlService) Status(ctx context.Context) (repos.DispatchControl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx)
	ret0, _ := ret[0].(repos.DispatchControl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockPauseControlServiceMockRecorder) Status(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockPauseControlService)(nil).Status), ctx)
}
