// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/pulse/internal/service (interfaces: ProjectorService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/projector_mock.go -package=mocks github.com/bete7512/pulse/internal/service ProjectorService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProjectorService is a mock of ProjectorService interface.
type MockProjectorService struct {
	ctrl     *gomock.Controller
	recorder *MockProjectorServiceMockRecorder
	isgomock struct{}
}

// MockProjectorServiceMockRecorder is the mock recorder for MockProjectorService.
type MockProjectorServiceMockRecorder struct {
	mock *MockProjectorService
}

// NewMockProjectorService creates a new mock instance.
func NewMockProjectorService(ctrl *gomock.Controller) *MockProjectorService {
	mock := &MockProjectorService{ctrl: ctrl}
	mock.recorder = &MockProjectorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectorService) EXPECT() *MockProjectorServiceMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockProjectorService) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockProjectorServiceMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockProjectorService)(nil).Run), ctx)
}
