// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/pulse/internal/service (interfaces: ScheduleService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/scheduleadmin_mock.go -package=mocks github.com/bete7512/pulse/internal/service ScheduleService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bete7512/pulse/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockScheduleService is a mock of ScheduleService interface.
type MockScheduleService struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleServiceMockRecorder
	isgomock struct{}
}

// MockScheduleServiceMockRecorder is the mock recorder for MockScheduleService.
type MockScheduleServiceMockRecorder struct {
	mock *MockScheduleService
}

// NewMockScheduleService creates a new mock instance.
func NewMockScheduleService(ctrl *gomock.Controller) *MockScheduleService {
	mock := &MockScheduleService{ctrl: ctrl}
	mock.recorder = &MockScheduleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleService) EXPECT() *MockScheduleServiceMockRecorder {
	return m.recorder
}

// CreateSchedule mocks base method.
func (m *MockScheduleService) CreateSchedule(ctx context.Context, sc domain.Schedule) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSchedule", ctx, sc)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSchedule indicates an expected call of CreateSchedule.
func (mr *MockScheduleServiceMockRecorder) CreateSchedule(ctx, sc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSchedule", reflect.TypeOf((*MockScheduleService)(nil).CreateSchedule), ctx, sc)
}

// DeleteSchedule mocks base method.
func (m *MockScheduleService) DeleteSchedule(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSchedule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSchedule indicates an expected call of DeleteSchedule.
func (mr *MockScheduleServiceMockRecorder) DeleteSchedule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSchedule", reflect.TypeOf((*MockScheduleService)(nil).DeleteSchedule), ctx, id)
}

// ListScheduleFires mocks base method.
func (m *MockScheduleService) ListScheduleFires(ctx context.Context, id string) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScheduleFires", ctx, id)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScheduleFires indicates an expected call of ListScheduleFires.
func (mr *MockScheduleServiceMockRecorder) ListScheduleFires(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScheduleFires", reflect.TypeOf((*MockScheduleService)(nil).ListScheduleFires), ctx, id)
}

// ListScheduleJobs mocks base method.
func (m *MockScheduleService) ListScheduleJobs(ctx context.Context, id string) ([]domain.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListScheduleJobs", ctx, id)
	ret0, _ := ret[0].([]domain.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListScheduleJobs indicates an expected call of ListScheduleJobs.
func (mr *MockScheduleServiceMockRecorder) ListScheduleJobs(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListScheduleJobs", reflect.TypeOf((*MockScheduleService)(nil).ListScheduleJobs), ctx, id)
}

// ListSchedules mocks base method.
func (m *MockScheduleService) ListSchedules(ctx context.Context) ([]domain.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSchedules", ctx)
	ret0, _ := ret[0].([]domain.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSchedules indicates an expected call of ListSchedules.
func (mr *MockScheduleServiceMockRecorder) ListSchedules(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSchedules", reflect.TypeOf((*MockScheduleService)(nil).ListSchedules), ctx)
}

// PauseSchedule mocks base method.
func (m *MockScheduleService) PauseSchedule(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseSchedule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseSchedule indicates an expected call of PauseSchedule.
func (mr *MockScheduleServiceMockRecorder) PauseSchedule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseSchedule", reflect.TypeOf((*MockScheduleService)(nil).PauseSchedule), ctx, id)
}

// ResumeSchedule mocks base method.
func (m *MockScheduleService) ResumeSchedule(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeSchedule", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResumeSchedule indicates an expected call of ResumeSchedule.
func (mr *MockScheduleServiceMockRecorder) ResumeSchedule(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeSchedule", reflect.TypeOf((*MockScheduleService)(nil).ResumeSchedule), ctx, id)
}
