// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/pulse/internal/service (interfaces: WatchdogService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/watchdog_mock.go -package=mocks github.com/bete7512/pulse/internal/service WatchdogService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWatchdogService is a mock of WatchdogService interface.
type MockWatchdogService struct {
	ctrl     *gomock.Controller
	recorder *MockWatchdogServiceMockRecorder
	isgomock struct{}
}

// MockWatchdogServiceMockRecorder is the mock recorder for MockWatchdogService.
type MockWatchdogServiceMockRecorder struct {
	mock *MockWatchdogService
}

// NewMockWatchdogService creates a new mock instance.
func NewMockWatchdogService(ctrl *gomock.Controller) *MockWatchdogService {
	mock := &MockWatchdogService{ctrl: ctrl}
	mock.recorder = &MockWatchdogServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatchdogService) EXPECT() *MockWatchdogServiceMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockWatchdogService) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockWatchdogServiceMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockWatchdogService)(nil).Run), ctx)
}
