// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/pulse/internal/repos (interfaces: DispatchControlRepo)
//
// Generated by this command:
//
//	mockgen -destination=mocks/dispatchcontrolrepo_mock.go -package=mocks github.com/bete7512/pulse/internal/repos DispatchControlRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repos "github.com/bete7512/pulse/internal/repos"
	gomock "go.uber.org/mock/gomock"
)

// MockDispatchControlRepo is a mock of DispatchControlRepo interface.
type MockDispatchControlRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDispatchControlRepoMockRecorder
	isgomock struct{}
}

// MockDispatchControlRepoMockRecorder is the mock recorder for MockDispatchControlRepo.
type MockDispatchControlRepoMockRecorder struct {
	mock *MockDispatchControlRepo
}

// NewMockDispatchControlRepo creates a new mock instance.
func NewMockDispatchControlRepo(ctrl *gomock.Controller) *MockDispatchControlRepo {
	mock := &MockDispatchControlRepo{ctrl: ctrl}
	mock.recorder = &MockDispatchControlRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDispatchControlRepo) EXPECT() *MockDispatchControlRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockDispatchControlRepo) Get(ctx context.Context) (repos.DispatchControl, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(repos.DispatchControl)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDispatchControlRepoMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDispatchControlRepo)(nil).Get), ctx)
}

// SetPaused mocks base method.
func (m *MockDispatchControlRepo) SetPaused(ctx context.Context, paused bool, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPaused", ctx, paused, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPaused indicates an expected call of SetPaused.
func (mr *MockDispatchControlRepoMockRecorder) SetPaused(ctx, paused, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPaused", reflect.TypeOf((*MockDispatchControlRepo)(nil).SetPaused), ctx, paused, reason)
}
