// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/pulse/internal/repos (interfaces: EventRepo)
//
// Generated by this command:
//
//	mockgen -destination=mocks/eventrepo_mock.go -package=mocks github.com/bete7512/pulse/internal/repos EventRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/bete7512/pulse/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockEventRepo is a mock of EventRepo interface.
type MockEventRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepoMockRecorder
	isgomock struct{}
}

// MockEventRepoMockRecorder is the mock recorder for MockEventRepo.
type MockEventRepoMockRecorder struct {
	mock *MockEventRepo
}

// NewMockEventRepo creates a new mock instance.
func NewMockEventRepo(ctrl *gomock.Controller) *MockEventRepo {
	mock := &MockEventRepo{ctrl: ctrl}
	mock.recorder = &MockEventRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepo) EXPECT() *MockEventRepoMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockEventRepo) Append(ctx context.Context, event domain.Event) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, event)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Append indicates an expected call of Append.
func (mr *MockEventRepoMockRecorder) Append(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockEventRepo)(nil).Append), ctx, event)
}

// AppendBatch mocks base method.
func (m *MockEventRepo) AppendBatch(ctx context.Context, events []domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendBatch", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendBatch indicates an expected call of AppendBatch.
func (mr *MockEventRepoMockRecorder) AppendBatch(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendBatch", reflect.TypeOf((*MockEventRepo)(nil).AppendBatch), ctx, events)
}

// FiresBySchedule mocks base method.
func (m *MockEventRepo) FiresBySchedule(ctx context.Context, scheduleID string) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FiresBySchedule", ctx, scheduleID)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FiresBySchedule indicates an expected call of FiresBySchedule.
func (mr *MockEventRepoMockRecorder) FiresBySchedule(ctx, scheduleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FiresBySchedule", reflect.TypeOf((*MockEventRepo)(nil).FiresBySchedule), ctx, scheduleID)
}

// ListEventsByTopics mocks base method.
func (m *MockEventRepo) ListEventsByTopics(ctx context.Context, topics []string) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEventsByTopics", ctx, topics)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEventsByTopics indicates an expected call of ListEventsByTopics.
func (mr *MockEventRepoMockRecorder) ListEventsByTopics(ctx, topics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEventsByTopics", reflect.TypeOf((*MockEventRepo)(nil).ListEventsByTopics), ctx, topics)
}

// LoadEventsForJob mocks base method.
func (m *MockEventRepo) LoadEventsForJob(ctx context.Context, jobID string) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadEventsForJob", ctx, jobID)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadEventsForJob indicates an expected call of LoadEventsForJob.
func (mr *MockEventRepoMockRecorder) LoadEventsForJob(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadEventsForJob", reflect.TypeOf((*MockEventRepo)(nil).LoadEventsForJob), ctx, jobID)
}

// OrphanedRunning mocks base method.
func (m *MockEventRepo) OrphanedRunning(ctx context.Context, grace time.Duration) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrphanedRunning", ctx, grace)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrphanedRunning indicates an expected call of OrphanedRunning.
func (mr *MockEventRepoMockRecorder) OrphanedRunning(ctx, grace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrphanedRunning", reflect.TypeOf((*MockEventRepo)(nil).OrphanedRunning), ctx, grace)
}
