// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/pulse/internal/repos (interfaces: JobRepo,ProjectionRepo)
//
// Generated by this command:
//
//	mockgen -destination=mocks/jobrepo_mock.go -package=mocks github.com/bete7512/pulse/internal/repos JobRepo,ProjectionRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/bete7512/pulse/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockJobRepo is a mock of JobRepo interface.
type MockJobRepo struct {
	ctrl     *gomock.Controller
	recorder *MockJobRepoMockRecorder
	isgomock struct{}
}

// MockJobRepoMockRecorder is the mock recorder for MockJobRepo.
type MockJobRepoMockRecorder struct {
	mock *MockJobRepo
}

// NewMockJobRepo creates a new mock instance.
func NewMockJobRepo(ctrl *gomock.Controller) *MockJobRepo {
	mock := &MockJobRepo{ctrl: ctrl}
	mock.recorder = &MockJobRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobRepo) EXPECT() *MockJobRepoMockRecorder {
	return m.recorder
}

// GetJob mocks base method.
func (m *MockJobRepo) GetJob(ctx context.Context, jobID string) (*domain.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJob", ctx, jobID)
	ret0, _ := ret[0].(*domain.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJob indicates an expected call of GetJob.
func (mr *MockJobRepoMockRecorder) GetJob(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJob", reflect.TypeOf((*MockJobRepo)(nil).GetJob), ctx, jobID)
}

// JobsBySchedule mocks base method.
func (m *MockJobRepo) JobsBySchedule(ctx context.Context, scheduleID string) ([]domain.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JobsBySchedule", ctx, scheduleID)
	ret0, _ := ret[0].([]domain.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JobsBySchedule indicates an expected call of JobsBySchedule.
func (mr *MockJobRepoMockRecorder) JobsBySchedule(ctx, scheduleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobsBySchedule", reflect.TypeOf((*MockJobRepo)(nil).JobsBySchedule), ctx, scheduleID)
}

// ListJobs mocks base method.
func (m *MockJobRepo) ListJobs(ctx context.Context) ([]domain.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobs", ctx)
	ret0, _ := ret[0].([]domain.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJobs indicates an expected call of ListJobs.
func (mr *MockJobRepoMockRecorder) ListJobs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobs", reflect.TypeOf((*MockJobRepo)(nil).ListJobs), ctx)
}

// MockProjectionRepo is a mock of ProjectionRepo interface.
type MockProjectionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockProjectionRepoMockRecorder
	isgomock struct{}
}

// MockProjectionRepoMockRecorder is the mock recorder for MockProjectionRepo.
type MockProjectionRepoMockRecorder struct {
	mock *MockProjectionRepo
}

// NewMockProjectionRepo creates a new mock instance.
func NewMockProjectionRepo(ctrl *gomock.Controller) *MockProjectionRepo {
	mock := &MockProjectionRepo{ctrl: ctrl}
	mock.recorder = &MockProjectionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectionRepo) EXPECT() *MockProjectionRepoMockRecorder {
	return m.recorder
}

// LaggingJobs mocks base method.
func (m *MockProjectionRepo) LaggingJobs(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LaggingJobs", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LaggingJobs indicates an expected call of LaggingJobs.
func (mr *MockProjectionRepoMockRecorder) LaggingJobs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LaggingJobs", reflect.TypeOf((*MockProjectionRepo)(nil).LaggingJobs), ctx)
}

// Upsert mocks base method.
func (m *MockProjectionRepo) Upsert(ctx context.Context, job domain.Job, seq int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, job, seq)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockProjectionRepoMockRecorder) Upsert(ctx, job, seq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockProjectionRepo)(nil).Upsert), ctx, job, seq)
}
