// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/pulse/internal/repos (interfaces: LivenessRepo)
//
// Generated by this command:
//
//	mockgen -destination=mocks/livenessrepo_mock.go -package=mocks github.com/bete7512/pulse/internal/repos LivenessRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockLivenessRepo is a mock of LivenessRepo interface.
type MockLivenessRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLivenessRepoMockRecorder
	isgomock struct{}
}

// MockLivenessRepoMockRecorder is the mock recorder for MockLivenessRepo.
type MockLivenessRepoMockRecorder struct {
	mock *MockLivenessRepo
}

// NewMockLivenessRepo creates a new mock instance.
func NewMockLivenessRepo(ctrl *gomock.Controller) *MockLivenessRepo {
	mock := &MockLivenessRepo{ctrl: ctrl}
	mock.recorder = &MockLivenessRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLivenessRepo) EXPECT() *MockLivenessRepoMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockLivenessRepo) Clear(ctx context.Context, jobID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", ctx, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clear indicates an expected call of Clear.
func (mr *MockLivenessRepoMockRecorder) Clear(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockLivenessRepo)(nil).Clear), ctx, jobID)
}

// Expired mocks base method.
func (m *MockLivenessRepo) Expired(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Expired", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Expired indicates an expected call of Expired.
func (mr *MockLivenessRepoMockRecorder) Expired(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Expired", reflect.TypeOf((*MockLivenessRepo)(nil).Expired), ctx)
}

// Mark mocks base method.
func (m *MockLivenessRepo) Mark(ctx context.Context, jobID, workerID string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mark", ctx, jobID, workerID, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mark indicates an expected call of Mark.
func (mr *MockLivenessRepoMockRecorder) Mark(ctx, jobID, workerID, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mark", reflect.TypeOf((*MockLivenessRepo)(nil).Mark), ctx, jobID, workerID, expiresAt)
}

// Renew mocks base method.
func (m *MockLivenessRepo) Renew(ctx context.Context, jobID, workerID string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Renew", ctx, jobID, workerID, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Renew indicates an expected call of Renew.
func (mr *MockLivenessRepoMockRecorder) Renew(ctx, jobID, workerID, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Renew", reflect.TypeOf((*MockLivenessRepo)(nil).Renew), ctx, jobID, workerID, expiresAt)
}
