// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bete7512/pulse/internal/repos (interfaces: ScheduleRepo)
//
// Generated by this command:
//
//	mockgen -destination=mocks/schedulerepo_mock.go -package=mocks github.com/bete7512/pulse/internal/repos ScheduleRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/bete7512/pulse/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockScheduleRepo is a mock of ScheduleRepo interface.
type MockScheduleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleRepoMockRecorder
	isgomock struct{}
}

// MockScheduleRepoMockRecorder is the mock recorder for MockScheduleRepo.
type MockScheduleRepoMockRecorder struct {
	mock *MockScheduleRepo
}

// NewMockScheduleRepo creates a new mock instance.
func NewMockScheduleRepo(ctrl *gomock.Controller) *MockScheduleRepo {
	mock := &MockScheduleRepo{ctrl: ctrl}
	mock.recorder = &MockScheduleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleRepo) EXPECT() *MockScheduleRepoMockRecorder {
	return m.recorder
}

// Advance mocks base method.
func (m *MockScheduleRepo) Advance(ctx context.Context, id string, occurrence, nextRunAt, lastRunAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Advance", ctx, id, occurrence, nextRunAt, lastRunAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Advance indicates an expected call of Advance.
func (mr *MockScheduleRepoMockRecorder) Advance(ctx, id, occurrence, nextRunAt, lastRunAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Advance", reflect.TypeOf((*MockScheduleRepo)(nil).Advance), ctx, id, occurrence, nextRunAt, lastRunAt)
}

// Create mocks base method.
func (m *MockScheduleRepo) Create(ctx context.Context, s domain.Schedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockScheduleRepoMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScheduleRepo)(nil).Create), ctx, s)
}

// Delete mocks base method.
func (m *MockScheduleRepo) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockScheduleRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockScheduleRepo)(nil).Delete), ctx, id)
}

// Due mocks base method.
func (m *MockScheduleRepo) Due(ctx context.Context, now time.Time, limit int) ([]domain.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Due", ctx, now, limit)
	ret0, _ := ret[0].([]domain.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Due indicates an expected call of Due.
func (mr *MockScheduleRepoMockRecorder) Due(ctx, now, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Due", reflect.TypeOf((*MockScheduleRepo)(nil).Due), ctx, now, limit)
}

// Get mocks base method.
func (m *MockScheduleRepo) Get(ctx context.Context, id string) (*domain.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*domain.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockScheduleRepoMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockScheduleRepo)(nil).Get), ctx, id)
}

// List mocks base method.
func (m *MockScheduleRepo) List(ctx context.Context) ([]domain.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]domain.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockScheduleRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockScheduleRepo)(nil).List), ctx)
}

// SetPaused mocks base method.
func (m *MockScheduleRepo) SetPaused(ctx context.Context, id string, paused bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPaused", ctx, id, paused)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPaused indicates an expected call of SetPaused.
func (mr *MockScheduleRepoMockRecorder) SetPaused(ctx, id, paused any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPaused", reflect.TypeOf((*MockScheduleRepo)(nil).SetPaused), ctx, id, paused)
}
